import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";
import "@uploadthing/react/styles.css";

import { cn } from "@/lib/utils"
import { Toaster } from "@/components/ui/sonner";
import type { Viewport } from 'next'
 
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
      <body className={cn(
          "min-h-screen bg-background font-sans",
          fontSans.variable
        )}>{children}
        <Toaster />
        </body>
    </html>
  );
}
